import cmbc from '../bank/cmbc'
import c9 from './c9'
import edg from './edg'
import fnc from './fnc'
import fpx from './fpx'
import geng from './geng'
import ig from './ig'
import jdg from './jdg'
import ra from './ra'
import rng from './rng'
import tes from './tes'
import tl from './tl'
import we from './we'

export default { tes, ig, fpx, we, jdg, edg, c9, fnc, geng, rng, tl, ra, cmbc }
